#! /usr/bin/python3

import os
import sys
import jwt
import socket
from datetime import datetime
import dateutil.parser
import argparse

CONF_FILE='/etc/bigbluebutton/bbb-auth-jwt'

local_timezone = datetime.now().astimezone().tzinfo

if os.path.isfile(CONF_FILE):
    exec(open(CONF_FILE).read())
else:
    import vnc_collaborate
    from vnc_collaborate import bigbluebutton
    JWT_KEY = bigbluebutton.securitySalt()

LOGIN_URL = 'https://' + socket.getfqdn() + '/login.cgi/'

parser = argparse.ArgumentParser(description='Generate login URL for a Big Blue Button server')
parser.add_argument('-e', '--expiration-time', type=str, required=True,
                    help='expiration time of tokens (defaults to midnight in local timezone if only date is given)')
parser.add_argument('-m', '--moderator', action="store_true",
                    help='generate moderator tokens')
parser.add_argument('name')
args = parser.parse_args()

try:
    exp = dateutil.parser.parse(args.expiration_time)
    if exp.tzinfo is None:
        exp = exp.replace(tzinfo = local_timezone)
except:
    raise Exception("Can't parse expiration time")

if args.moderator:
    role = 'm'
else:
    role = 'v'

message = {'sub' : args.name, 'role' : role, 'exp' : exp}

print('Expiration time:', exp.strftime('%c %Z'))

print(message)

JWT = jwt.encode(message, JWT_KEY)

print(LOGIN_URL + JWT.decode())
